REQUIRED_MERCHANT = [
    'PICKUP_EXTERNAL_BUSINESS_ID',
    # 'PICKUP_BUSINESS_NAME', # recommended
]
REQUIRED_PICKUP =[
    'PICKUP_TIME',
    'PICKUP_WINDOW',
    'PICKUP_ADDRESS',
    'PICKUP_EXTERNAL_STORE_ID',
    'PICKUP_PHONE_NUMBER',
]
REQUIRED_DROPOFF=[
    'DROPOFF_TIME',
    'DROPOFF_WINDOW',
    'DROPOFF_ADDRESS',
    'DROPOFF_ADDRESS_COMPONENTS',
    'DROPOFF_CONTACT_GIVEN_NAME',
    'DROPOFF_PHONE_NUMBER',
]
RECOMMENDED=[
    'TIP',
    'ORDER_VALUE',
    'PICKUP_BUSINESS_NAME',
    'PICKUP_INSTRUCTIONS',
    'DROPOFF_INSTRUCTIONS',
    'CONTACTLESS_DROPOFF',
    'ITEMS',
]

